version: '2.4'
services:
  # Description: Jaeger all-in-one instance
  # (https://www.jaegertracing.io/docs/2.16/getting-started/) for distributed tracing.
  #
  # Disk: none
  # Ports exposed to other Sourcegraph services: 5778/TCP 4317/TCP 4318/TCP
  # Ports exposed to the public internet: none
  # Ports exposed to site admins only: 16686/HTTP
  #
  jaeger:
    container_name: jaeger
    image: 'index.docker.io/sourcegraph/jaeger-all-in-one:7.5.4453@sha256:d049be70dc7a71f05efba919726a1e19ceeb4bc9339c990fa8fed2fc6a4d6e39'
    cpus: 0.5
    mem_limit: '512m'
    ports:
      # Query port
      - '0.0.0.0:16686:16686'
      # OTLP ports
      - '0.0.0.0:4317:4317' # gRPC
      - '0.0.0.0:4318:4318' # HTTP
      # Remote sampling
      - '0.0.0.0:5778:5778'
    networks:
      - sourcegraph
    restart: always
    command: ['--config=/etc/jaeger/jaeger-config.yaml']

  # Configure collector to send traces to Jaeger
  otel-collector:
    environment:
      - JAEGER_HOST=jaeger
      - JAEGER_OTLP_GRPC_PORT=4317
    command: ['--config', '/etc/otel-collector/configs/jaeger.yaml']

  # Let frontend proxy to Jaeger interface
  sourcegraph-frontend-0:
    environment:
      - 'JAEGER_SERVER_URL=http://jaeger:16686'

  sourcegraph-frontend-internal:
    environment:
      - 'JAEGER_SERVER_URL=http://jaeger:16686'
