$schema: 'http://json.schemastore.org/buildkite'
steps:
  - label: ':docker:'
    command: .buildkite/validate-docker-compose.sh
    agents:
      queue: 'baremetal'
  - label: ':lipstick:'
    command: .buildkite/prettier-check.sh
    agents:
      queue: 'baremetal'
  - label: ':rice:'
    command: .buildkite/test.sh pure-docker-test
    agents:
      queue: 'baremetal'
    env:
      VAGRANT_RUN_ENV: 'CI'
  - label: ':rice:'
    command: .buildkite/test.sh docker-compose-test
    agents:
      queue: 'baremetal'
    env:
      VAGRANT_RUN_ENV: 'CI'
  - wait: ~
    continue_on_failure: true
  - label: ':broom:'
    command: .buildkite/cleanup.sh
    agents:
      queue: 'baremetal'
