$schema: 'http://json.schemastore.org/buildkite'
env:
  IMAGE: 'e2e-2e61d9153-2021-06-22t15-18-00z'
  VAGRANT_RUN_ENV: 'CI'
steps:
  - label: ':docker:'
    command: .buildkite/validate-docker-compose.sh
    agents:
      queue: 'vagrant'
  - label: ':lipstick:'
    command: .buildkite/prettier-check.sh
    agents:
      queue: 'vagrant'
  - label: ":git: :sleuth_or_spy:"
    command: .buildkite/verify-release/verify-release.sh      
  - label: ':rice: pure-docker-test'
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    agents:
      queue: 'vagrant'
    env:
      TEST_TYPE: 'pure-docker-test'
  - label: ':rice: docker-compose-test'
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    agents:
      queue: 'vagrant'
    env:
      TEST_TYPE: 'docker-compose-test'
