$schema: 'http://json.schemastore.org/buildkite'
env:
  IMAGE: 'e2e-cd59179f-2020-12-04t18-24-14z'
  VAGRANT_RUN_ENV: 'CI'
steps:
  - label: ':docker:'
    command: .buildkite/validate-docker-compose.sh
    agents:
      queue: 'baremetal'
  - label: ':lipstick:'
    command: .buildkite/prettier-check.sh
    agents:
      queue: 'baremetal'
  - label: ':rice: pure-docker-test'
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    agents:
      queue: 'baremetal'
    env:
      TEST_TYPE: 'pure-docker-test'
  - label: ':rice: docker-compose-test'
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    agents:
      queue: 'baremetal'
    env:
      TEST_TYPE: 'docker-compose-test'
