$schema: "http://json.schemastore.org/buildkite"
env:
  # Build this image in sourcegraph/infrastructure by running `make e2e` in `gcp/images`
  IMAGE: "e2e-db8a40720-2024-08-26t08-44-10z"
  VAGRANT_RUN_ENV: "CI"
steps:
  - label: ":docker:"
    command: .buildkite/validate-docker-compose.sh
    agents: { queue: "vagrant" }

  - label: ":lipstick:"
    command: .buildkite/prettier-check.sh
    agents: { queue: "vagrant" }

  - label: ":git: :sleuth_or_spy:"
    command: .buildkite/verify-release/verify-release.sh
    agents: { queue: standard }

  - label: ":rice: pure-docker-test"
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    env:
      TEST_TYPE: "pure-docker-test"
    agents: { queue: "vagrant" }

  - label: ":rice: docker-compose-test"
    command: .buildkite/vagrant-run.sh docker-test
    artifact_paths: ./*.log
    env:
      TEST_TYPE: "docker-compose-test"
    agents: { queue: "vagrant" }

  # This runs the Checkov Terraform Code scanner
  # https://www.checkov.io/
  - command: .buildkite/ci-checkov.sh
    label: ":lock: security - checkov"
    agents: { queue: "standard" }
    soft_fail: true

  # Please keep in mind that the release manifest uses specific branch names when creating releases.
  # Therefore, if you update them, or if you decide to change how we detect what kind of build we're dealing
  # with, please update this file as well.
  - label: "(internal) Release: test"
    if: build.branch =~ /^internal\/release-.*/
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run test --workdir=. --config-from-commit

  - label: "(promote) Release: test"
    if: build.branch =~ /^promote\/release-.*/
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run test --workdir=. --config-from-commit

  - wait

  - label: "(internal) Release: finalize"
    if: build.branch =~ /^internal\/release-.*/
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run internal finalize --workdir=. --config-from-commit


  - label: "(promote) Release: finalize"
    if: build.branch =~ /^promote\/release-.*/
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run promote-to-public finalize --workdir=. --config-from-commit

