{
 "title": "Containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values(process_start_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process Uptime [rate-10s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$container\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container CPU [all cores]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance)(container:process_cpu_seconds_total:sum{instance=~\"$container\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage [RSS]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$container\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$container\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage [VSZ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$container\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}