{
 "title": "Gitserver",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gitserver",
    "query": "label_values(src_gitserver_exec_duration_seconds_bucket, instance)"
   },
   { "name": "percentile", "query": ".90, .95, .98, .99" },
   {
    "name": "command",
    "query": "label_values(src_gitserver_exec_duration_seconds_bucket, cmd)"
   }
  ]
 },
 "panels": [
  {
   "title": "P$percentile by Command [rate-10m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(src_gitserver_exec_duration_seconds_bucket{cmd=~\"$command\", instance=~\"$gitserver\"}[10m])) by (le, cmd))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "QPS by Command [rate-10m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_gitserver_exec_duration_seconds_count{status=~\"[0-9]+\",cmd=~\"$command\",instance=~\"$gitserver\"}[10m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Disk Space Remaining",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "min(src_gitserver_disk_space_available{instance=~\"$gitserver\"}) BY (instance) / 1000 / 1000 / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Running Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(src_gitserver_exec_running{instance=~\"$gitserver\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS by Exit Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, cmd)(rate(src_gitserver_exec_duration_seconds_count{instance=~\"$gitserver\"}[10m]))",
     "legendFormat": "{{cmd}}: {{status}}"
    }
   ]
  }
 ]
}