{
 "title": "Searcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "searcher",
    "query": "label_values(searcher_service_running, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Running Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_service_running{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Requests Served by Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_service_request_total{instance=~\"$searcher\"}",
     "legendFormat": "{{code}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Errors [rate-10m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_errors:rate10m{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests [rate-10m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_requests:rate10m{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Archive Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Archive Cache Failed Fetches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_store_fetch_failed{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Archive Cache Fetch Queue Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_store_fetch_queue_size{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Archive Cache Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "searcher_store_cache_size_bytes{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Archive Cache Evictions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_store_evictions{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Archive Cache Running Fetches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "searcher_store_fetching{instance=~\"$searcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}