apiVersion: 1

datasources:
  - name: pgsql
    type: postgres
    url: $GRAFANA_PGSQL_HOST:$GRAFANA_PGSQL_PORT
    user: $GRAFANA_PGSQL_USER
    database: $GRAFANA_PGSQL_DATABASE
    secureJsonData:
      password: $GRAFANA_PGSQL_PASSWORD
    jsonData:
      sslmode: $GRAFANA_PGSQL_SSLMODE
