#!/usr/bin/env bash

set -eu
cd $BUILDKITE_BUILD_CHECKOUT_PATH

env

if ! command -v asdf &> /dev/null
then
    echo "skipping asdf, TODO: ask Dave to add asdf to baremetal image"
    exit
fi

echo "Installing asdf dependencies as defined in '$BUILDKITE_BUILD_CHECKOUT_PATH/.tool-versions':"
asdf install
