name: Update tags
on:
  workflow_dispatch:
    inputs:
      semver:
        required: true
      branch:
        required: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'

      # generate update
      - name: Pin tags to ${{ github.event.inputs.semver }}
        run: tools/update-docker-tags.sh "${{ github.event.inputs.semver }}"
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.branch }}
          branch: upgrade-${{ github.event.inputs.branch }}
          title: 'Upgrade ${{ github.event.inputs.branch }} to ${{ github.event.inputs.semver }}'
          body: |
            Upgrade the `${{ github.event.inputs.branch }}` branch's Sourcegraph Docker images to enforce constraints `${{ github.event.inputs.semver }}`.

            This pull request was generate by [this run](https://github.com/sourcegraph/deploy-sourcegraph/actions/runs/${{ github.run_id }})
          commit-message: 'Upgrade to Sourcegraph ${{ github.event.inputs.semver }}'
